name: Minimal Source Build

on:
  push:
    branches: [main]

jobs:
  generate-and-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Minimal Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Force Recreate Flutter Project
        run: |
          flutter create --platforms=windows,macos,linux --no-overwrite .

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Platform Dependencies
        run: |
          case "${{ runner.os }}" in
            Linux)
              sudo apt-get install -y libgtk-3-dev
              ;;
            macOS)
              sudo softwareupdate --install-rosetta --agree-to-license
              ;;
          esac

      - name: Build Application
        run: |
          flutter pub get
          case "${{ runner.os }}" in
            Linux)   flutter build linux --release ;;
            macOS)   flutter build macos --release ;;
            Windows) flutter build windows --release ;;
          esac

      - name: Archive Artifacts
        run: |
          case "${{ runner.os }}" in
            Linux)
              cd build/linux/x64/release/bundle
              zip -r ${{ github.workspace }}/PCL-Newer-Project-Linux-x64.zip .
              ;;
            macOS)
              cd build/macos/Build/Products/Release
              zip -r ${{ github.workspace }}/PCL-Newer-Project-macOS-x64.zip .
              ;;
            Windows)
              cd build/windows/runner/Release
              7z a ${{ github.workspace }}/PCL-Newer-Project-Windows-x64.zip ./*
              ;;
          esac

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-build
          path: ${{ github.workspace }}/PCL-Newer-Project-${{ runner.os }}-x64.zip