name: Minimal Source Build

on:
  push:
    branches: [main]

jobs:
  generate-and-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Start Build
        run: |
          flutter pub get
          flutter build windows
          flutter build linux
          flutter build macos
      # - name: Pack all by zip
      #   run: |
