name: Minimal Source Build

on:
  push:
    branches: [main]

jobs:
  generate-and-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Initialize Project
        run: flutter create --platforms=windows,macos,linux --no-overwrite .
      - name: Start Build
        run: |
          flutter pub get
          if ("${{ runner.os }}" -eq "Linux") {
            sudo apt-get update -y
            sudo apt-get install -y ninja-build libgtk-3-dev
            flutter build linux --release
          } elseif ("${{ runner.os }}" -eq "macOS") {
            flutter build macos --release
          } else {
            flutter build windows --release
          }
        shell: pwsh
      - name: Zip all releases
        run: |
          mkdir releases
          if ("${{ runner.os }}" -eq "Linux") {
            zip -9 -r "./releases/PCL-Newer-Project-Linux.zip" "build/linux/x64/release/bundle"
          } elseif ("${{ runner.os }}" -eq "macOS") {
            zip -9 -r "./releases/PCL-Newer-Project-macOS.zip" "build/macos/Build/Products/Release"
          } else {
            7z a "./releases/PCL-Newer-Project-Windows.zip" "build/windows/x64/runner/Release/*"
          }
        shell: pwsh
      - name: Upload all Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }}-bundle
          path: ./releases/PCL-Newer-Project-${{ runner.os }}.zip